--                                                  mk1               mk2                mk3
-- mining_speed                                     0.5               1                  2
-- module_specification.module_slots                3                 4                  5
-- energy_source.emissions_per_minute               10                8                  6
-- energy_usage                                     90kW              180kW              270kW
-- resource_searching_radius                        2.49              3.49               4.49
-- max_health                                       300               600                900

data.raw["mining-drill"]["electric-mining-drill"].fast_replaceable_group = "electric-mining-drill"
data.raw["mining-drill"]["electric-mining-drill"].next_upgrade = "electric-mining-drill-mk2"

local drill2 = table.deepcopy(data.raw["mining-drill"]["electric-mining-drill"])
drill2.name = "electric-mining-drill-mk2"
drill2.icon = "__FactorioExtended-Plus-Machines__/graphics/icons/electric-mining-drill-mk2.png"
drill2.icon_size = 32
drill2.minable.result = drill2.name
drill2.mining_speed = 1
drill2.module_specification.module_slots = 4
drill2.energy_source.emissions_per_minute = 8
drill2.energy_usage = "180kW"
drill2.resource_searching_radius = 3.49
drill2.max_health = 600
drill2.next_upgrade = "electric-mining-drill-mk3"

for _, direction in pairs({"north", "east", "south", "west"}) do
    local short = string.upper(string.sub(direction, 1, 1))
    -- animations
    drill2.animations[direction].filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-" .. short .. ".png"
    drill2.animations[direction].animation_speed = 1
    drill2.animations[direction].hr_version.filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-" .. short .. ".png"
    drill2.animations[direction].hr_version.animation_speed = 1
    -- input_fluid_patch_sprites
    drill2.input_fluid_patch_sprites[direction].filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-" .. short .. "-patch.png"
    drill2.input_fluid_patch_sprites[direction].hr_version.filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-" .. short .. "-patch.png"
end

local drill3 = table.deepcopy(data.raw["mining-drill"]["electric-mining-drill"])
drill3.name = "electric-mining-drill-mk3"
drill3.icon = "__FactorioExtended-Plus-Machines__/graphics/icons/electric-mining-drill-mk3.png"
drill3.icon_size = 64
drill3.icon_mipmaps = 4
drill3.minable.result = drill3.name
drill3.mining_speed = 2
drill3.module_specification.module_slots = 5
drill3.energy_source.emissions_per_minute = 6
drill3.energy_usage = "270kW"
drill3.resource_searching_radius = 4.49
drill3.max_health = 900
drill3.next_upgrade = nil

for _, direction in pairs({"north", "east", "south", "west"}) do
    local short = string.upper(string.sub(direction, 1, 1))
    -- animations
    drill3.animations[direction].filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk3/electric-mining-drill-" .. short .. ".png"
    drill3.animations[direction].animation_speed = 2
    drill3.animations[direction].hr_version.filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk3/hr-electric-mining-drill-" .. short .. ".png"
    drill3.animations[direction].hr_version.animation_speed = 2
    -- input_fluid_patch_sprites
    drill3.input_fluid_patch_sprites[direction].filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk3/electric-mining-drill-" .. short .. "-patch.png"
    drill3.input_fluid_patch_sprites[direction].hr_version.filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk3/hr-electric-mining-drill-" .. short .. "-patch.png"
end

data:extend({drill2, drill3})

-- {
--     type = "mining-drill",
--     name = "electric-mining-drill-mk2",
--     icon = "__FactorioExtended-Plus-Machines__/graphics/icons/electric-mining-drill-mk2.png",
--     icon_size = 32,
--     flags = {"placeable-neutral", "player-creation"},
--     minable = {mining_time = 0.3, result = "electric-mining-drill-mk2"},
--     max_health = 600,
--     resource_categories = {"basic-solid"},
--     corpse = "big-remnants",
--     collision_box = {{ -1.4, -1.4}, {1.4, 1.4}},
--     selection_box = {{ -1.5, -1.5}, {1.5, 1.5}},
--     vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
--     input_fluid_box = (not data.is_demo) and
--     {
--       production_type = "input-output",
--       pipe_picture = assembler2pipepictures(),
--       pipe_covers = pipecoverspictures(),
--       base_area = 1,
--       height = 2,
--       base_level = -1,
--       pipe_connections =
--       {
--         { position = {-2, 0} },
--         { position = {2, 0} },
--         { position = {0, 2} }
--       }
--     } or nil,
--     working_sound =
--     {
--       sound =
--       {
--         filename = "__base__/sound/electric-mining-drill.ogg",
--         volume = 0.75
--       },
--       apparent_volume = 1.5,
--     },
--     vehicle_impact_sound =  { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
--     animations =
--     {
--       north =
--       {
--         priority = "high",
--         filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-N.png",
--         line_length = 8,
--         width = 98,
--         height = 113,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(0, -8.5),
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-N.png",
--           line_length = 8,
--           width = 196,
--           height = 226,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(0, -8),
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       east =
--       {
--         priority = "high",
--         filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-E.png",
--         line_length = 8,
--         width = 105,
--         height = 98,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(3.5, -1),
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-E.png",
--           line_length = 8,
--           width = 211,
--           height = 197,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(3.75, -1.25),
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       south =
--       {
--         priority = "high",
--         filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-S.png",
--         line_length = 8,
--         width = 98,
--         height = 109,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(0, -1.5),
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-S.png",
--           line_length = 8,
--           width = 196,
--           height = 219,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(0, -1.25),
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       west =
--       {
--         priority = "high",
--         filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-W.png",
--         line_length = 8,
--         width = 105,
--         height = 98,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(-3.5, -1),
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-W.png",
--           line_length = 8,
--           width = 211,
--           height = 197,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(-3.75, -0.75),
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       }
--     },
--     shadow_animations =
--     {
--       north =
--       {
--         priority = "high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-N-drill-shadow.png",
--         flags = { "shadow" },
--         line_length = 8,
--         width = 101,
--         height = 111,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(1.5, -7.5),
--         draw_as_shadow = true,
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-N-drill-shadow.png",
--           flags = { "shadow" },
--           line_length = 8,
--           width = 201,
--           height = 223,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(1.25, -7.25),
--           draw_as_shadow = true,
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       east =
--       {
--         priority = "high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-E-drill-shadow.png",
--         flags = { "shadow" },
--         line_length = 8,
--         width = 110,
--         height = 97,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(6, -0.5),
--         draw_as_shadow = true,
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-E-drill-shadow.png",
--           flags = { "shadow" },
--           line_length = 8,
--           width = 221,
--           height = 195,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(6.25, -0.25),
--           draw_as_shadow = true,
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       south =
--       {
--         priority = "high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-S-drill-shadow.png",
--         flags = { "shadow" },
--         line_length = 8,
--         width = 100,
--         height = 103,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(1, 2.5),
--         draw_as_shadow = true,
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-S-drill-shadow.png",
--           flags = { "shadow" },
--           line_length = 8,
--           width = 200,
--           height = 206,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(1, 2.5),
--           draw_as_shadow = true,
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       west =
--       {
--         priority = "high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-W-drill-shadow.png",
--         flags = { "shadow" },
--         line_length = 8,
--         width = 114,
--         height = 97,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(1, -0.5),
--         draw_as_shadow = true,
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-W-drill-shadow.png",
--           flags = { "shadow" },
--           line_length = 8,
--           width = 229,
--           height = 195,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(1.25, -0.25),
--           draw_as_shadow = true,
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       }
--     },
--     input_fluid_patch_sprites =
--     {
--       north =
--       {
--         priority = "extra-high",
--         filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-N-patch.png",
--         width = 100,
--         height = 111,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(0, -6.5),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-N-patch.png",
--           width = 200,
--           height = 222,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-0.5, -6.5),
--           scale = 0.5
--         }
--       },
--       east =
--       {
--         priority = "extra-high",
--         filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-E-patch.png",
--         width = 100,
--         height = 110,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(0, -6),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-E-patch.png",
--           width = 200,
--           height = 219,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(0, -5.75),
--           scale = 0.5
--         }
--       },
--       south =
--       {
--         priority = "extra-high",
--         filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-S-patch.png",
--         width = 100,
--         height = 113,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(0, -7.5),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-S-patch.png",
--           width = 200,
--           height = 226,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-0.5, -7.5),
--           scale = 0.5
--         }
--       },
--       west =
--       {
--         priority = "extra-high",
--         filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/electric-mining-drill-W-patch.png",
--         width = 100,
--         height = 108,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(0, -5),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__FactorioExtended-Plus-Machines__/graphics/entity/electric-mining-drill-mk2/hr-electric-mining-drill-W-patch.png",
--           width = 200,
--           height = 220,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-0.5, -6),
--           scale = 0.5
--         }
--       }
--     },
--     input_fluid_patch_shadow_sprites =
--     {
--       north =
--       {
--         priority = "extra-high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-N-patch-shadow.png",
--         flags = { "shadow" },
--         width = 110,
--         height = 98,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(5, 0),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-N-patch-shadow.png",
--           flags = { "shadow" },
--           width = 220,
--           height = 197,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(5, -0.25),
--           scale = 0.5
--         }
--       },
--       east =
--       {
--         priority = "extra-high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-E-patch-shadow.png",
--         flags = { "shadow" },
--         width = 112,
--         height = 98,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(6, 0),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-E-patch-shadow.png",
--           flags = { "shadow" },
--           width = 224,
--           height = 198,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(6, 0),
--           scale = 0.5
--         }
--       },
--       south =
--       {
--         priority = "extra-high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-S-patch-shadow.png",
--         flags = { "shadow" },
--         width = 110,
--         height = 98,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(5, 0),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-S-patch-shadow.png",
--           flags = { "shadow" },
--           width = 220,
--           height = 197,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(5, -0.25),
--           scale = 0.5
--         }
--       },
--       west =
--       {
--         priority = "extra-high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-W-patch-shadow.png",
--         flags = { "shadow" },
--         width = 110,
--         height = 98,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(5, 0),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-W-patch-shadow.png",
--           flags = { "shadow" },
--           width = 220,
--           height = 197,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(5, -0.25),
--           scale = 0.5
--         }
--       }
--     },
--     input_fluid_patch_shadow_animations =
--     {
--       north =
--       {
--         priority = "high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-N-drill-received-shadow.png",
--         tint = { r=0.5, g=0.5, b=0.5, a=0.5 },
--         line_length = 8,
--         width = 100,
--         height = 102,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(-1, -3),
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-N-drill-received-shadow.png",
--           tint = { r=0.5, g=0.5, b=0.5, a=0.5 },
--           line_length = 8,
--           width = 204,
--           height = 206,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(-0.5, -2),
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       east =
--       {
--         priority = "high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-E-drill-received-shadow.png",
--         tint = { r=0.5, g=0.5, b=0.5, a=0.5 },
--         line_length = 8,
--         width = 102,
--         height = 98,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(0, -2),
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-E-drill-received-shadow.png",
--           tint = { r=0.5, g=0.5, b=0.5, a=0.5 },
--           line_length = 8,
--           width = 204,
--           height = 209,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(-0.5, -1.25),
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       south =
--       {
--         priority = "high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-S-drill-received-shadow.png",
--         tint = { r=0.5, g=0.5, b=0.5, a=0.5 },
--         line_length = 8,
--         width = 100,
--         height = 98,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(-1, -1),
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-S-drill-received-shadow.png",
--           tint = { r=0.5, g=0.5, b=0.5, a=0.5 },
--           line_length = 8,
--           width = 204,
--           height = 204,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(-0.5, -2.5),
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       },
--       west =
--       {
--         priority = "high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-W-drill-received-shadow.png",
--         tint = { r=0.5, g=0.5, b=0.5, a=0.5 },
--         line_length = 8,
--         width = 96,
--         height = 99,
--         frame_count = 64,
--         direction_count = 1,
--         shift = util.by_pixel(0, -1.5),
--         run_mode = "forward-then-backward",
--         hr_version =
--         {
--           priority = "high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-W-drill-received-shadow.png",
--           tint = { r=0.5, g=0.5, b=0.5, a=0.5 },
--           line_length = 8,
--           width = 198,
--           height = 206,
--           frame_count = 64,
--           direction_count = 1,
--           shift = util.by_pixel(1, -2),
--           run_mode = "forward-then-backward",
--           scale = 0.5
--         }
--       }
--     },
--     input_fluid_patch_window_sprites =
--     {
--       north =
--       {
--         priority = "extra-high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-N-window-background.png",
--         width = 72,
--         height = 54,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(-1, 1),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-N-window-background.png",
--           width = 142,
--           height = 107,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-1, 0.75),
--           scale = 0.5
--         }
--       },
--       east =
--       {
--         priority = "extra-high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-E-window-background.png",
--         width = 51,
--         height = 74,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(-11.5, -11),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-E-window-background.png",
--           width = 104,
--           height = 147,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-11, -11.25),
--           scale = 0.5
--         }
--       },
--       south =
--       {
--         priority = "extra-high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-S-window-background.png",
--         width = 71,
--         height = 44,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(-1.5, -29),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-S-window-background.png",
--           width = 141,
--           height = 86,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-1.75, -29),
--           scale = 0.5
--         }
--       },
--       west =
--       {
--         priority = "extra-high",
--         filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-W-window-background.png",
--         width = 41,
--         height = 69,
--         frame_count = 1,
--         direction_count = 1,
--         shift = util.by_pixel(11.5, -11.5),
--         hr_version =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-W-window-background.png",
--           width = 80,
--           height = 137,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(11.5, -11.25),
--           scale = 0.5
--         }
--       }
--     },

--     input_fluid_patch_window_flow_sprites =
--     {
--       {
--         north =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-N-fluid-flow.png",
--           width = 68,
--           height = 50,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-2, -1),
--           hr_version =
--           {
--             priority = "extra-high",
--             filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-N-fluid-flow.png",
--             width = 136,
--             height = 99,
--             frame_count = 1,
--             direction_count = 1,
--             shift = util.by_pixel(-2.5, -0.75),
--             scale = 0.5
--           }
--         },
--         east =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-E-fluid-flow.png",
--           width = 41,
--           height = 70,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-11.5, -11),
--           hr_version =
--           {
--             priority = "extra-high",
--             filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-E-fluid-flow.png",
--             width = 82,
--             height = 139,
--             frame_count = 1,
--             direction_count = 1,
--             shift = util.by_pixel(-11.5, -11.25),
--             scale = 0.5
--           }
--         },
--         south =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-S-fluid-flow.png",
--           width = 68,
--           height = 40,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-2, -29),
--           hr_version =
--           {
--             priority = "extra-high",
--             filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-S-fluid-flow.png",
--             width = 136,
--             height = 80,
--             frame_count = 1,
--             direction_count = 1,
--             shift = util.by_pixel(-2.5, -29.5),
--             scale = 0.5
--           }
--         },
--         west =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-W-fluid-flow.png",
--           width = 42,
--           height = 70,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(11, -11),
--           hr_version =
--           {
--             priority = "extra-high",
--             filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-W-fluid-flow.png",
--             width = 83,
--             height = 140,
--             frame_count = 1,
--             direction_count = 1,
--             shift = util.by_pixel(10.75, -11),
--             scale = 0.5
--           }
--         }
--       },
--     },
--     input_fluid_patch_window_base_sprites =
--     {
--       {
--         north =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-N-fluid-background.png",
--           width = 70,
--           height = 48,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-2, 0),
--           hr_version =
--           {
--             priority = "extra-high",
--             filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-N-fluid-background.png",
--             width = 138,
--             height = 94,
--             frame_count = 1,
--             direction_count = 1,
--             shift = util.by_pixel(-2, 0),
--             scale = 0.5
--           }
--         },
--         east =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-E-fluid-background.png",
--           width = 42,
--           height = 70,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-12, -11),
--           hr_version =
--           {
--             priority = "extra-high",
--             filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-E-fluid-background.png",
--             width = 84,
--             height = 138,
--             frame_count = 1,
--             direction_count = 1,
--             shift = util.by_pixel(-12, -11),
--             scale = 0.5
--           }
--         },
--         south =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-S-fluid-background.png",
--           width = 70,
--           height = 40,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(-2, -29),
--           hr_version =
--           {
--             priority = "extra-high",
--             filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-S-fluid-background.png",
--             width = 138,
--             height = 80,
--             frame_count = 1,
--             direction_count = 1,
--             shift = util.by_pixel(-2, -29),
--             scale = 0.5
--           }
--         },
--         west =
--         {
--           priority = "extra-high",
--           filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-W-fluid-background.png",
--           width = 42,
--           height = 69,
--           frame_count = 1,
--           direction_count = 1,
--           shift = util.by_pixel(12, -10.5),
--           hr_version =
--           {
--             priority = "extra-high",
--             filename = "__base__/graphics/entity/electric-mining-drill/hr-electric-mining-drill-W-fluid-background.png",
--             width = 83,
--             height = 137,
--             frame_count = 1,
--             direction_count = 1,
--             shift = util.by_pixel(11.75, -10.75),
--             scale = 0.5
--           }
--         }
--       },
--     },
--     mining_speed = 1,
--     energy_source =
--     {
--       type = "electric",
--       -- will produce this much * energy pollution units per tick
--       emissions_per_minute = 8,
--       usage_priority = "secondary-input"
--     },
--     energy_usage = "180kW",
--     resource_searching_radius = 3.49,
--     vector_to_place_result = {0, -1.85},
--     module_specification =
--     {
--       module_slots = 4
--     },
--     radius_visualisation_picture =
--     {
--       filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-radius-visualization.png",
--       width = 10,
--       height = 10
--     },
--     monitor_visualization_tint = {r=78, g=173, b=255},
--     fast_replaceable_group = "mining-drill",
--     circuit_wire_connection_points = circuit_connector_definitions["electric-mining-drill"].points,
--     circuit_connector_sprites = circuit_connector_definitions["electric-mining-drill"].sprites,
--     circuit_wire_max_distance = default_circuit_wire_max_distance,
--   },
